"""add new table and columns

Revision ID: 58ee3dbd8ac3
Revises: c0482fbc47a2
Create Date: 2025-08-26 23:25:45.204047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58ee3dbd8ac3'
down_revision: Union[str, None] = 'c0482fbc47a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_type', sa.Enum('CONDUCT_3_TRAINING', 'CONDUCT_5_TRAINING', 'CONDUCT_7_TRAINING', 'PLAY_BLITZ', 'PLAY_2_BLITZ', 'GOAL_IN_MATCH', 'RICH_SEMI_FINAL_BLITZ', 'RICH_FINAL_WIN_BLITZ', 'REGISTER_ON_MATCH', 'MVP_TWO', 'MVP_TWO_HALF', 'MVP_THREE', name='statisticstype'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_key_payment_id'), table_name='key_payment')
    op.drop_table('key_payment')
    op.drop_index(op.f('ix_change_position_payment_id'), table_name='change_position_payment')
    op.drop_table('change_position_payment')
    op.add_column('characters', sa.Column('tier_ciper', sa.String(length=255), nullable=True))
    op.add_column('characters', sa.Column('count_play_blitz', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_rich_semi_final_blitz', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_rich_final_looser_blitz', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_rich_final_winner_blitz', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_go_to_gym', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_goal_on_match', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_register_on_match', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_mvp_two_and_more', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_mvp_two_half_and_more', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('count_mvp_three_and_more', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'count_mvp_three_and_more')
    op.drop_column('characters', 'count_mvp_two_half_and_more')
    op.drop_column('characters', 'count_mvp_two_and_more')
    op.drop_column('characters', 'count_register_on_match')
    op.drop_column('characters', 'count_goal_on_match')
    op.drop_column('characters', 'count_go_to_gym')
    op.drop_column('characters', 'count_rich_final_winner_blitz')
    op.drop_column('characters', 'count_rich_final_looser_blitz')
    op.drop_column('characters', 'count_rich_semi_final_blitz')
    op.drop_column('characters', 'count_play_blitz')
    op.drop_column('characters', 'tier_ciper')
    op.create_table('change_position_payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('position', mysql.ENUM('MIDFIELDER', 'DEFENDER', 'GOALKEEPER', 'ATTACKER'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], name=op.f('change_position_payment_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_change_position_payment_id'), 'change_position_payment', ['id'], unique=False)
    op.create_table('key_payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], name=op.f('key_payment_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_key_payment_id'), 'key_payment', ['id'], unique=False)
    op.drop_table('stats')
    # ### end Alembic commands ###
