"""edit name character column

Revision ID: 6e6e42c4c047
Revises: 58ee3dbd8ac3
Create Date: 2025-08-26 23:32:47.724359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e6e42c4c047'
down_revision: Union[str, None] = '58ee3dbd8ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_payment_id'), table_name='key_payment')
    op.drop_table('key_payment')
    op.drop_index(op.f('ix_change_position_payment_id'), table_name='change_position_payment')
    op.drop_table('change_position_payment')
    op.add_column('characters', sa.Column('tier_cipher', sa.String(length=255), nullable=True))
    op.drop_column('characters', 'tier_ciper')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('tier_ciper', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('characters', 'tier_cipher')
    op.create_table('change_position_payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('position', mysql.ENUM('MIDFIELDER', 'DEFENDER', 'GOALKEEPER', 'ATTACKER'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], name=op.f('change_position_payment_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_change_position_payment_id'), 'change_position_payment', ['id'], unique=False)
    op.create_table('key_payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], name=op.f('key_payment_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_key_payment_id'), 'key_payment', ['id'], unique=False)
    # ### end Alembic commands ###
