"""create blitzs table

Revision ID: c0482fbc47a2
Revises: 8c67d2c3d8d6
Create Date: 2025-08-04 00:30:55.539851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0482fbc47a2'
down_revision: Union[str, None] = '8c67d2c3d8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blitz_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blitzs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blitz_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('blitz_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('goals_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_score', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['blitz_id'], ['blitzs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['blitz_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('league_fight', 'type_league',
               existing_type=mysql.ENUM('BEST_LEAGUE', 'DEFAULT_LEAGUE', 'TOP_20_CLUB_LEAGUE', 'NEW_CLUB_LEAGUE'),
               nullable=True)
    op.add_column('match_character', sa.Column('count_score', sa.Float(), server_default='0', nullable=False))
    op.create_unique_constraint(None, 'reminder_characters', ['character_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminder_characters', type_='unique')
    op.drop_column('match_character', 'count_score')
    op.alter_column('league_fight', 'type_league',
               existing_type=mysql.ENUM('BEST_LEAGUE', 'DEFAULT_LEAGUE', 'TOP_20_CLUB_LEAGUE', 'NEW_CLUB_LEAGUE'),
               nullable=False)
    op.drop_table('blitz_characters')
    op.drop_table('blitzs')
    op.drop_table('blitz_team')
    # ### end Alembic commands ###
