from enum import Enum

class StatisticsType(Enum):
    # --- Tier 1 ---
    CONDUCT_3_TRAINING = "CONDUCT_3_TRAINING"
    CONDUCT_5_TRAINING = "CONDUCT_5_TRAINING"
    CONDUCT_7_TRAINING = "CONDUCT_7_TRAINING"
    PLAY_BLITZ = "PLAY_BLITZ"
    PLAY_2_BLITZ = "PLAY_2_BLITZ"

    # --- Tier 2 ---
    GOAL_IN_MATCH = "GOAL_IN_MATCH"
    RICH_SEMI_FINAL_BLITZ = "RICH_SEMI_FINAL_BLITZ"
    RICH_FINAL_WIN_BLITZ = "RICH_FINAL_WIN_BLITZ"

    # --- Tier 3 ---
    REGISTER_ON_MATCH = "REGISTER_ON_MATCH"
    MVP_TWO = "MVP_TWO"
    MVP_TWO_HALF = "MVP_TWO_HALF"
    MVP_THREE = "MVP_THREE"